natgw_pkg.sv
natgw_ram.sv
natgw_fifo.sv
natgw_parser.sv
natgw_lookup.sv
natgw_state.sv
natgw_rewrite.sv
natgw_regs.sv
natgw_tx_merge.sv
natgw_switch.sv
natgw_shim.sv
../lib/taxi/src/axis/rtl/taxi_axis_async_fifo_adapter.f
../lib/taxi/src/axis/rtl/taxi_axis_fifo.sv
../lib/taxi/src/axis/rtl/taxi_axis_register.sv
../lib/taxi/src/axis/rtl/taxi_axis_arb_mux.f
